name: cartracker
description: GPS car tracker

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.2
  mapbox_gl: 
  uuid: 
  sqflite:
  fluttercontactpicker:
  path: 
  path_provider: 
  provider: 
  telephony: 
  flutter_colorpicker: 
  image_picker:
  fluttertoast:
  flutter_slidable: 
  url_launcher:
  geolocator: 
  salomon_bottom_bar: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: 1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sdf/
